title: "Kshiteej Sheth"
title_html: "<b>Kshiteej Sheth</b>"
description: "PhD Student, EPFL."
author: "Kshiteej Sheth"
email: "kshiteejsheth96@gmail.com"
profile_picture: "/personal_picture_2.jpg"
github_username: ksheth96
scholar_url: "https://scholar.google.com/citations?user=LpgWaeUAAAAJ&hl=en"

remote_theme: gaalcaras/academic
plugins:
  - jekyll-remote-theme
